default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>
  pool: <%= ENV['RAILS_MAX_THREADS'] %>
  timeout: 5000
  reconnect: true

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['DB_NAME'] %>

production:
  <<: *default
